apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-halyard
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    namespace: default
    name: halyard-home-oes-spinnaker-halyard-0
  persistentVolumeReclaimPolicy: Retain
  #storageClassName: standard
  hostPath:
    path: "/home/bhaveen_g/PVDIR/halyard"
