apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-spinnaker-minio
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: oes-minio
    namespace: default
  persistentVolumeReclaimPolicy: Retain
  #storageClassName: standard
  hostPath:
    path: "/home/bhaveen_g/PVDIR/minio"
