apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redis-data-spinnaker
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: redis-data-oes-redis-master-0
    namespace: default
  persistentVolumeReclaimPolicy: Retain
  #storageClassName: standard
  hostPath:
    path: "/home/bhaveen_g/PVDIR/redis"
